version: '2.3'

services:
  apache:
    container_name: proxy_apache
    image: oracolo/apache
    mem_limit: 200MB
    ports:
     - 80:80
  proxy:
    container_name: localproxy
    image: oracolo/proxy
    mem_limit: 300MB
    ports:
    - 8080:8080
    environment:
      - REDIS_DB_HOST=redis
      - REDIS_DB_PORT=6379
      - KEYSTORE_FILE_NAME=keystore.jks
    depends_on:
      - redis
      - apache
  redis:
    container_name: proxy_redis
    image: redis
    ports:
    - 6380:6379
  cadvisor:
    image: 'google/cadvisor:latest'
    container_name: cadvisor
    mem_limit: 100MB
    volumes:
          - /:/rootfs:ro
          - /var/run:/var/run:ro
          - /sys:/sys:ro
          - /var/lib/docker/:/var/lib/docker:ro
          - /dev/disk:/dev/disk/:ro
    ports:
        - 8082:8080