version: '2.3'

services:
  apache:
    container_name: localapache
    build: ./apache
    ports:
      - 80:80
  proxy:
    container_name: localproxy
    build: .
    mem_limit: 200MB
    ports:
      - 8080:8080
    environment:
      - REDIS_DB_HOST=redis
      - REDIS_DB_PORT=6379
      - KEYSTORE_FILE_NAME=keystore.jks
    depends_on:
      - redis
      - apache
  redis:
    container_name: localproxy_redis
    image: redis
    ports:
      - 6380:6379